<?php


namespace App\Voyager\Http\Controllers;

use App\DBContext\PostReview;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class PostReviewController extends VoyagerBaseController
{
    public function index(Request $request)
    {
        return parent::index($request);
    }

    protected function applyRelationQueryBuilder(Model $context, Model $model, array $dependsOnFields): EloquentBuilder
    {
        if ($model instanceof PostReview){
            if ($context->exists){
                $model = $model->where('id','<>', $context->id);
            }

            foreach ($dependsOnFields as $depend){
                $field = $depend['field'];
                $operator = $depend['operator'];
                $value = $depend['value'];
                $model = $model->where($field, $operator, $value);
            }
            /** @noinspection PhpIncompatibleReturnTypeInspection */
            return $model;
        }
        return $model::query();
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'post_id'=>'required|exists:posts,id',
            'parent_id'=>'exists:post_reviews,id,post_id,'.$request->input('post_id')
        ]);
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @param $id
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'post_id'=>'required|exists:posts,id',
            'parent_id'=>'exists:post_reviews,id,post_id,'.$request->input('post_id')
        ]);

        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
}
